// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::physics_world_tick_type::PhysicsWorldTick;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `physics_world_ticks`.
///
/// Obtain a handle from the [`PhysicsWorldTicksTableAccess::physics_world_ticks`] method on [`super::RemoteTables`],
/// like `ctx.db.physics_world_ticks()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_world_ticks().on_insert(...)`.
pub struct PhysicsWorldTicksTableHandle<'ctx> {
    imp: __sdk::TableHandle<PhysicsWorldTick>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `physics_world_ticks`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhysicsWorldTicksTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhysicsWorldTicksTableHandle`], which mediates access to the table `physics_world_ticks`.
    fn physics_world_ticks(&self) -> PhysicsWorldTicksTableHandle<'_>;
}

impl PhysicsWorldTicksTableAccess for super::RemoteTables {
    fn physics_world_ticks(&self) -> PhysicsWorldTicksTableHandle<'_> {
        PhysicsWorldTicksTableHandle {
            imp: self
                .imp
                .get_table::<PhysicsWorldTick>("physics_world_ticks"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhysicsWorldTicksInsertCallbackId(__sdk::CallbackId);
pub struct PhysicsWorldTicksDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhysicsWorldTicksTableHandle<'ctx> {
    type Row = PhysicsWorldTick;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PhysicsWorldTick> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhysicsWorldTicksInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsWorldTicksInsertCallbackId {
        PhysicsWorldTicksInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhysicsWorldTicksInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhysicsWorldTicksDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsWorldTicksDeleteCallbackId {
        PhysicsWorldTicksDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhysicsWorldTicksDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PhysicsWorldTick>("physics_world_ticks");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PhysicsWorldTicksUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhysicsWorldTicksTableHandle<'ctx> {
    type UpdateCallbackId = PhysicsWorldTicksUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhysicsWorldTicksUpdateCallbackId {
        PhysicsWorldTicksUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhysicsWorldTicksUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PhysicsWorldTick>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PhysicsWorldTick>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `physics_world_ticks`,
/// which allows point queries on the field of the same name
/// via the [`PhysicsWorldTicksIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_world_ticks().id().find(...)`.
pub struct PhysicsWorldTicksIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PhysicsWorldTick, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhysicsWorldTicksTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `physics_world_ticks`.
    pub fn id(&self) -> PhysicsWorldTicksIdUnique<'ctx> {
        PhysicsWorldTicksIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhysicsWorldTicksIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PhysicsWorldTick> {
        self.imp.find(col_val)
    }
}
