// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerShootArgs {}

impl From<PlayerShootArgs> for super::Reducer {
    fn from(args: PlayerShootArgs) -> Self {
        Self::PlayerShoot
    }
}

impl __sdk::InModule for PlayerShootArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerShootCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_shoot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_shoot {
    /// Request that the remote module invoke the reducer `player_shoot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_shoot`] callbacks.
    fn player_shoot(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_shoot`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerShootCallbackId`] can be passed to [`Self::remove_on_player_shoot`]
    /// to cancel the callback.
    fn on_player_shoot(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> PlayerShootCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_shoot`],
    /// causing it not to run in the future.
    fn remove_on_player_shoot(&self, callback: PlayerShootCallbackId);
}

impl player_shoot for super::RemoteReducers {
    fn player_shoot(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("player_shoot", PlayerShootArgs {})
    }
    fn on_player_shoot(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> PlayerShootCallbackId {
        PlayerShootCallbackId(self.imp.on_reducer(
            "player_shoot",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerShoot {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_player_shoot(&self, callback: PlayerShootCallbackId) {
        self.imp.remove_on_reducer("player_shoot", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_shoot`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_shoot {
    /// Set the call-reducer flags for the reducer `player_shoot` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_shoot(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_shoot for super::SetReducerFlags {
    fn player_shoot(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("player_shoot", flags);
    }
}
